### ISSUE TITLE
how to build in vs 2010?

### ISSUE THREAD

**Issue by amankapur** [fuCtor/QAMQP#7]
I'm a little new at vs2010. 

How do I build this? 

I've opened the sln file

and I get this: 

1>------ Build started: Project: QAMQP, Configuration: Debug Win32 ------
1>  Moc'ing amqp.h...
1>  The system cannot find the path specified.
1>  The system cannot find the path specified.
1>  The system cannot find the path specified.
1>  Moc'ing amqp_channel.h...
1>  Moc'ing amqp_connection.h...
1>  Moc'ing amqp_exchange.h...
1>  The system cannot find the path specified.
1>  Moc'ing amqp_network.h...
1>  Moc'ing amqp_queue.h...
1>  The system cannot find the path specified.
1>  The system cannot find the path specified.
1>  Moc'ing test.h...
1>  The system cannot find the path specified.
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB6006: "cmd.exe" exited with code 3.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by fuCtor** [comment]
All Qt environment setup? Another project are building? You can create solution from PRO file.

**Comment by adambadura** [comment]
I succeeded with building in Visual Studio 2010.

Here are my steps:
1. After opening the provided `.sln` file VS asked me to convert the old project format. I did. No issues here.
2. While building I got errors of unknown `QSslError` class (and `QSslSocket` as well I believe - but `QSslError` was the first one).
3. I changed Qt from licensed 4.7.4 I got from someone (at work) to a fresh, just downloaded 4.8.3 open version and the errors disappeared.

Yet the project output is an `.exe` file rather than a library (be it either `.lib` or `.dll`). And this is set both in the VS project and in Qt project.

Are library users expected to change that themselves and rebuild? Which one (`.lib` or `.dll`) is advised?

**Comment by spaceindaver** [comment]
I also built this expecting a library. Are there plans to make it into one or is it up to the user to alter it?

**Comment by adambadura** [comment]
By playing around a bit with the configuration I established you need a `StaticLibrary` rather than `DynamicLibrary` (even thou I somehow preferred a `.dll`). This is because the code does not make any exports and thus resulting `.dll` is useless.

But this does not end issues. I didn't manage to make it work. It seems the `.exe` resulting from original configuration did connect to [RabbitMQ](http://www.rabbitmq.com/) on `localhost` and set up an `Exchange` (I did observe the `test.test2` name).

But I failed to make a connection from my own code. It seems on socket level the connection was made but `Client::isConnected()` returned `false` anyway and nothing else later on worked. No errors reported, logged or thrown.

Another disturbing issue was that function `login` called after `connect` is empty.

I'm somewhat afraid this library might not be mature yet. And I'm not sure it ever will.

**Comment by fuCtor** [comment]
Project as you can see is console application. I use this code "as is" in my application and build-in as source code. Maybe it's bad solution, but as is.

Show your code. All methods is async. And you should wait signal that connection established.

Sorry for my english :)

**Comment by adambadura** [comment]
How should I wait? By a call to what on what?

My code runs as Qt Windows service. I will be able to provide more details tomorrow when at work.

**Comment by fuCtor** [comment]
Event loop running?

Ok, will be wait more information.

**Comment by adambadura** [comment]
Not sure now without checking the actual code.

But the code is run within [`QtService` from `QtSolutions` archives](http://qt.gitorious.org/qt-solutions/qt-solutions/trees/master/qtservice) which is template-parametrized with `QCoreApplication`. And I think it does have an event loop.

Also most tests I did using just an ordinary `QCoreApplication`-based console application (much simpler to debug).

**Comment by adambadura** [comment]
OK, for testing I used a simple `QCoreApplication` and run its loop with a call to `exec` and it seems to help somewhat.

---

Also I added a slot for `QAMQP::Client::connected` signal and proceeded in that slot rather than immediately. It did help somewhat. The client did connect (`isConnected()` returns `true` in that slot). Yet note that I didn't knew you had to do that since it is not what you show in example (the `Test` class both here in `README.md` and in code).

---

But here the success ends. Nothing more seems to work. This is my slot code:

``` c++
void Listener::onClientConnected()
{
  assert( theClient->isConnected() );

  theExchange.reset( theClient->createExchange( "Listener.Exchange" ) );

  connect(
    theExchange.get(),
    SIGNAL( declared() ),
    SLOT( onExchangeDeclared() )
  );
  connect(
    theExchange.get(),
    SIGNAL( binded() ),
    SLOT( onExchangeBinded() )
  );

  theExchange->declare( "fanout" );

  theQueue.reset(
    theClient->createQueue(
      "Listener.Queue",
      theExchange->channelNumber()
    )
  );

  connect(
    theQueue.get(),
    SIGNAL( declared() ),
    SLOT( onQueueDeclared() )
  );
  connect(
    theQueue.get(),
    SIGNAL( binded( bool ) ),
    SLOT( onQueueBinded( bool ) )
  );
  connect(
    theQueue.get(),
    SIGNAL( messageRecieved() ),
    SLOT( onQueueMessageRecieved() )
  );

  theQueue->declare();

  theExchange->bind( theQueue.get() );

  theExchange->publish( "My First Message Ever!", "Listener.MyKey" );
}
```

None of the slots gets ever called and here it is what console window shows:

```
Connection:
>> Start
>> version_major: 0
>> version_minor: 9
         version :  QVariant(QString, "2.8.7")
         product :  QVariant(QString, "RabbitMQ")
         platform :  QVariant(QString, "Erlang/OTP")
         capabilities : FIELD_TABLE
         copyright :  QVariant(QString, "Copyright (C) 2007-2012 VMware, Inc.")

         information :  QVariant(QString, "Licensed under the MPL.  See http://w
ww.rabbitmq.com/")
>> mechanisms: PLAIN AMQPLAIN
>> locales: en_US
Connection:
>> Tune
>> channel_max: 0
>> frame_max: 131072
>> heartbeat: 0
Connection:
>> OpenOK
Connection:
>> CLOSE
>> code: 504
>> text: CHANNEL_ERROR - expected 'channel.open'
>> class-id: 60
>> method-id: 40
AMQP Socket Error:  "Unknown error"
Exchange  "Listener.Exchange"  disconnected
```

after a short while:

```
QAbstractSocket::connectToHost() called when already looking up or connecting/co
nnected to "localhost"
```

and then after a bit longer while:

```
AMQP Socket Error:  "The remote host closed the connection"
```

then over and over again the same. Apparently the code tried to reconnect.

---

On my [RabbitMQ Management](http://www.rabbitmq.com/management.html) web site the connection was listed with following parameters:
1. Protocol = `AMQP 0-9-1`
2. Name = `[::1]:50367 -> [::1]:5672`
3. Channels = `0`

But I did not spot neither any exchange nor queue nor channels.

---

In final notes let me state that I'm very new in both [RabbitMQ](http://www.rabbitmq.com/) and AMQP in general. I just have to use it to connect to an app and receive a simple list of paths. So I might by trying to do something that is supposed to fail. But I mostly followed what the `Test` class/example showed.

---

Also I wanted to ask how about failures. How am I supposed to know about failures? To what slot should I connect? Or what values to check?

**Comment by fuCtor** [comment]
You try publish message before exchange declaration confirmed.

Rewrite like this:

```
void Listener::onExchangeDeclared() 
{
   // your code here
   theExchange->publish( "My First Message Ever!", "Listener.MyKey" );
   // your code here
}
```

**Comment by adambadura** [comment]
I did that change. The disconnections no longer appear and output ends on:

```
Connection:
>> OpenOK
```

Yet non of the connected slots (and thus neither the `publish` function) are ever called.
